### ISSUE TITLE
Immediately after the setup, it crashed.

### ISSUE THREAD

**Issue by onweer** [xmrminer01102018/VegaToolsNConfigs#3]
![image](https://user-images.githubusercontent.com/11755669/52999175-0f514580-3460-11e9-8af1-4cab13fd9713.png)

**Comment by xmrminer01102018** [comment]
Did you run setPPT.sh and/or  setSMClockVoltages.sh before running setGPUOC.sh?

**Comment by xmrminer01102018** [comment]
No more issue I guess.
