### ISSUE TITLE
How to create new pptable file for vega56

### ISSUE THREAD

**Issue by artful172** [xmrminer01102018/VegaToolsNConfigs#6]
I need create new pptable file for vega56

>     <mem>
>       <p0 enabled="1" clock="167" vddc="800" />
>       <p1 enabled="1" clock="500" vddc="800" />
>       <p2 enabled="1" clock="700" vddc="900" />
>       <p3 enabled="1" clock="950" vddc="900" />
>     </mem>
>     <core>
>       <p0 enabled="1" clock="852" vddc="800" />
>       <p1 enabled="1" clock="852" vddc="800" />
>       <p2 enabled="1" clock="852" vddc="800" />
>       <p3 enabled="1" clock="852" vddc="800" />
>       <p4 enabled="1" clock="852" vddc="800" />
>       <p5 enabled="1" clock="852" vddc="800" />
>       <p6 enabled="1" clock="852" vddc="800" />
>       <p7 enabled="1" clock="852" vddc="800" />
>     </core>
> 

how to geterate new ppt file ?

**Comment by xmrminer01102018** [comment]
Sorry for the delay.  Try this.

https://github.com/halsafar/Vega64SoftPowerTableEditor

Suppose to work with Vega 56 and Vega 64.

**Comment by xmrminer01102018** [comment]
See EXPERIMENTAL section.
